name: TradeShop
version: 2.0.0
main: org.shanerx.tradeshop.TradeShop
api-version: 1.14
load: POSTWORLD

authors: [Lori00, KillerOfPie]
description: A new powerful trading plugin.
website: https://www.spigotmc.org/resources/tradeshop.32762/

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ts]