name: TradeShop
version: 1.5
author: Lori00
main: org.shanerx.tradeshop.TradeShop

description: A new powerful trading plugin.

commands:
  tradeshop:
    description: Core command for TradeShop
    aliases: [ts]
